export const REGISTER_ACTIONS = {
  REGISTER: "REGISTER_ACTIONS_REGISTER",
  UPLOAD_IMAGE: "REGISTER_ACTIONS_UPLOAD_IMAGE",
  CLEAR_IMAGE: "REGISTER_ACTIONS_CLEAR_IMAGE"
};

export const registerAction = values => {
  return { type: REGISTER_ACTIONS.REGISTER, datos: values };
};
